"""Custom MCP tools for the people search agent (local-first, PDL fallback)."""

import json

from claude_agent_sdk import create_sdk_mcp_server, tool

from src.local_search import save_pdl_to_people, search_local as run_local_search
from src.param_refiner import relax_params, suggest_narrowing
from src.pdl_client import enrich_person, search_people as pdl_search_people
from src.query_parser import parse_query
from src.result_processor import score_and_summarize


LOCAL_SEARCH_SCHEMA = {
    "type": "object",
    "properties": {
        "query": {
            "type": "string",
            "description": "2-6 English keywords for local full-text search, such as 'machine learning engineer'.",
        },
        "country": {
            "type": "string",
            "description": "Optional country filter in lowercase English, such as 'united states'.",
        },
        "seniority": {
            "type": "string",
            "description": "Optional seniority filter, such as 'senior', 'manager', 'director', or 'entry'.",
        },
        "industry": {
            "type": "string",
            "description": "Optional industry filter in lowercase English.",
        },
        "has_email": {
            "type": "boolean",
            "description": "Optional filter. True means only people with email.",
        },
        "page": {
            "type": "integer",
            "minimum": 0,
            "description": "0-based page number. Default 0.",
        },
        "size": {
            "type": "integer",
            "minimum": 1,
            "maximum": 100,
            "description": "Results per page. Default 10.",
        },
    },
    "required": ["query"],
    "additionalProperties": False,
}

PARSE_SEARCH_QUERY_SCHEMA = {
    "type": "object",
    "properties": {
        "query": {
            "type": "string",
            "description": "The user's search description in any language.",
        },
    },
    "required": ["query"],
    "additionalProperties": False,
}

PDL_SEARCH_SCHEMA = {
    "type": "object",
    "properties": {
        "sql_query": {
            "type": "string",
            "description": "PDL SQL generated by parse_search_query.",
        },
        "size": {
            "type": "integer",
            "minimum": 1,
            "maximum": 100,
            "description": "Results per page. Default 10.",
        },
        "scroll_token": {
            "type": "string",
            "description": "Optional PDL scroll token for pagination.",
        },
    },
    "required": ["sql_query"],
    "additionalProperties": False,
}

SCORE_AND_FILTER_SCHEMA = {
    "type": "object",
    "properties": {
        "user_query": {"type": "string"},
        "people_json": {"type": "string"},
        "threshold": {"type": "integer", "minimum": 1, "maximum": 10},
        "scenario": {
            "type": "string",
            "enum": ["recruiting", "marketing", "kol", "sales"],
        },
    },
    "required": ["user_query", "people_json"],
    "additionalProperties": False,
}

RELAX_PARAMS_SCHEMA = {
    "type": "object",
    "properties": {
        "original_query": {"type": "string"},
        "sql_query": {"type": "string"},
        "result_count": {"type": "integer", "minimum": 0},
        "scenario": {
            "type": "string",
            "enum": ["recruiting", "marketing", "kol", "sales"],
        },
    },
    "required": ["original_query", "sql_query", "result_count"],
    "additionalProperties": False,
}

SUGGEST_NARROWING_SCHEMA = {
    "type": "object",
    "properties": {
        "original_query": {"type": "string"},
        "sql_query": {"type": "string"},
        "result_count": {"type": "integer", "minimum": 0},
        "scenario": {
            "type": "string",
            "enum": ["recruiting", "marketing", "kol", "sales"],
        },
    },
    "required": ["original_query", "sql_query", "result_count"],
    "additionalProperties": False,
}

PDL_ENRICH_SCHEMA = {
    "type": "object",
    "properties": {
        "linkedin_url": {
            "type": "string",
            "description": "LinkedIn profile URL. Preferred when available.",
        },
        "email": {
            "type": "string",
            "description": "Work email address for the person.",
        },
        "name": {
            "type": "string",
            "description": "Person name. Use together with company when linkedin_url and email are unavailable.",
        },
        "company": {
            "type": "string",
            "description": "Company name. Use together with name when linkedin_url and email are unavailable.",
        },
    },
    "additionalProperties": False,
}


def _text(content: str) -> dict:
    return {"content": [{"type": "text", "text": content}]}


def _extract_local_filters(args: dict) -> dict:
    filters = {}
    if args.get("country"):
        filters["country"] = args["country"]
    if args.get("seniority"):
        filters["seniority"] = args["seniority"]
    if args.get("industry"):
        filters["industry"] = args["industry"]
    if args.get("has_email"):
        filters["has_email"] = True
    return filters


@tool(
    "local_search",
    "FIRST search tool for every new search request. "
    "Search the local database for free. "
    "Always call this before parse_search_query or pdl_search. "
    "Only include optional filters you already know.",
    LOCAL_SEARCH_SCHEMA,
)
async def local_search_tool(args: dict) -> dict:
    query = args["query"].strip()
    page = args.get("page", 0)
    size = args.get("size", 10)
    filters = _extract_local_filters(args)

    print(f"[local_search] query={query!r}, filters={filters}, page={page}, size={size}")

    try:
        result = await run_local_search(query, filters=filters, page=page, size=size)
        result["source"] = "local"
        return _text(json.dumps(result, ensure_ascii=False, indent=2))
    except Exception as e:
        print(f"[local_search] error: {e}")
        return _text(json.dumps({
            "total": 0,
            "people": [],
            "has_more": False,
            "page": page,
            "source": "none",
            "message": f"Local search error: {e}",
        }, ensure_ascii=False, indent=2))


@tool(
    "parse_search_query",
    "Generate a PDL SQL query from the user's natural-language description. "
    "Use this only after local_search returned total=0 or a local-search error.",
    PARSE_SEARCH_QUERY_SCHEMA,
)
async def parse_search_query_tool(args: dict) -> dict:
    try:
        params = parse_query(args["query"])
        return _text(json.dumps(params, ensure_ascii=False, indent=2))
    except (json.JSONDecodeError, IndexError) as e:
        return _text(f"Error parsing query: {e}")


@tool(
    "pdl_search",
    "Search the global People Data Labs database with a SQL query. "
    "Consumes PDL search quota. "
    "Use this only after local_search returned 0 results and parse_search_query produced sql_query.",
    PDL_SEARCH_SCHEMA,
)
async def pdl_search_tool(args: dict) -> dict:
    params = {
        "sql_query": args["sql_query"],
        "size": args.get("size", 10),
    }
    if args.get("scroll_token"):
        params["scroll_token"] = args["scroll_token"]

    try:
        results = await pdl_search_people(params)
        people = results.get("people", [])

        if people:
            try:
                await save_pdl_to_people(people, source="pdl_search")
            except Exception:
                pass

        output = {
            "total": results.get("total_entries", 0),
            "people": people,
            "has_more": bool(results.get("scroll_token")) or len(people) >= params["size"],
            "page": 0,
            "source": "pdl",
            "scroll_token": results.get("scroll_token"),
        }
        if results.get("error"):
            output["message"] = results["error"]
        return _text(json.dumps(output, ensure_ascii=False, indent=2))
    except Exception as e:
        return _text(json.dumps({
            "total": 0,
            "people": [],
            "has_more": False,
            "page": 0,
            "source": "none",
            "message": f"PDL search error: {e}",
        }, ensure_ascii=False, indent=2))


@tool(
    "score_and_filter_results",
    "Use LLM to score, filter, and summarize search results based on user intent and scenario. "
    "Use this after local_search or pdl_search when the result set is noisy or large.",
    SCORE_AND_FILTER_SCHEMA,
)
async def score_and_filter_tool(args: dict) -> dict:
    try:
        people = json.loads(args["people_json"])
    except json.JSONDecodeError as e:
        return _text(f"Invalid people JSON: {e}")

    threshold = args.get("threshold", 4)
    scenario = args.get("scenario", "recruiting")
    try:
        result = score_and_summarize(args["user_query"], people, threshold, scenario)
        return _text(json.dumps(result, ensure_ascii=False, indent=2))
    except (json.JSONDecodeError, IndexError) as e:
        return _text(f"Scoring error: {e}")


@tool(
    "auto_relax_params",
    "When a PDL search returns 0 or very few results, automatically relax the SQL query.",
    RELAX_PARAMS_SCHEMA,
)
async def auto_relax_params_tool(args: dict) -> dict:
    try:
        scenario = args.get("scenario", "recruiting")
        result = relax_params(args["original_query"], args["sql_query"], args["result_count"], scenario)
        return _text(json.dumps(result, ensure_ascii=False, indent=2))
    except (json.JSONDecodeError, IndexError) as e:
        return _text(f"Relax error: {e}")


@tool(
    "suggest_narrowing",
    "When a search returns too many results, generate follow-up questions to narrow the search.",
    SUGGEST_NARROWING_SCHEMA,
)
async def suggest_narrowing_tool(args: dict) -> dict:
    try:
        scenario = args.get("scenario", "recruiting")
        result = suggest_narrowing(args["original_query"], args["sql_query"], args["result_count"], scenario)
        return _text(json.dumps(result, ensure_ascii=False, indent=2))
    except (json.JSONDecodeError, IndexError) as e:
        return _text(f"Narrowing error: {e}")


@tool(
    "pdl_enrich",
    "Get full profile details for one person via PDL enrichment. "
    "Consumes 1 credit per successful lookup.",
    PDL_ENRICH_SCHEMA,
)
async def pdl_enrich_tool(args: dict) -> dict:
    params = {k: v for k, v in args.items() if v}
    if not params:
        return _text("Need linkedin_url, email, or name+company.")

    if not params.get("linkedin_url") and not params.get("email"):
        if not (params.get("name") and params.get("company")):
            return _text("Need linkedin_url, email, or name+company.")

    try:
        result = await enrich_person(params)
        if "error" in result:
            return _text(f"Enrich error: {result['error']}")

        try:
            await save_pdl_to_people([result], source="pdl_enrich")
        except Exception:
            pass

        return _text(json.dumps(result, ensure_ascii=False, indent=2))
    except Exception as e:
        return _text(f"PDL enrich error: {e}")


def create_tools_server():
    """Create the MCP server with all people search tools."""
    return create_sdk_mcp_server(
        "people-search-tools",
        tools=[
            local_search_tool,
            parse_search_query_tool,
            pdl_search_tool,
            score_and_filter_tool,
            auto_relax_params_tool,
            suggest_narrowing_tool,
            pdl_enrich_tool,
        ],
    )
